language: node_js
node_js:
- "8"
sudo: required
addons:
  apt:
    packages:
    - google-chrome-stable
install:
- npm install -g protractor
- npm install -g grunt
- npm install -g gulp
- webdriver-manager update
script:
- npm test